name: AP-Survival
version: '1.0'
main: de.dervonnebe.aps.APSurvival
api-version: '1.21'
author: dervonnebe
description: Watch out Website
website: https://dervonnebe.de/ap/survival
commands:
    apsurvival:
        description: Main command for AP-Survival
        usage: /<command>
        aliases: [aps]
    gamemode:
        description: Setze den Gamemode.
        usage: /<command> <0,1,2,3,a,s,c,sp,survival,adventure,creative,spectator> [spieler]
        aliases:
            - gm
    teleport:
        description: Teleportiere dich zu einem Spieler.
        usage: /<command> <spieler,location>
        aliases:
            - tp
    msg:
        description: Sende eine private Nachricht.
        usage: /<command> <spieler> <nachricht>
        aliases:
            - m
            - tell
            - whisper
            - w
    reply:
        description: Antworte auf eine private Nachricht.
        usage: /<command> <nachricht>
        aliases:
            - r

permissions:
    aps.admin:
        description: Permission for all admin commands
        default: op
    aps.user:
        description: Permission for all user commands
        default: true
    aps.command.reply:
        description: Permission to reply to private messages
        default: true
    aps.command.msg:
        description: Permission to send private messages
        default: true
    aps.command.msg.receive:
        description: Permission to receive private messages
        default: true
    aps.command.msg.send:
        description: Permission to send private messages
        default: true
    aps.command.teleport:
        description: Permission to teleport to players
        default: op
    aps.command.gamemode:
        description: Permission to change the gamemode
        default: op