name: AP-Survival
version: '1.0'
main: de.dervonnebe.aps.APSurvival
api-version: '1.20'
authors: [DerVonNebe]
description: Ein Plugin für den AP-Survival Server
website: https://dervonnebe.de/ap/survival

softdepend: [PlaceholderAPI]

commands:
    addCommand:

    apsurvival:
        description: "Main command for AP-Survival"
        usage: "/<command>"
        aliases:
            - aps

    gamemode:
        description: "Setze den Gamemode."
        usage: "/<command> <0,1,2,3,a,s,c,sp,survival,adventure,creative,spectator> [spieler]"
        aliases:
            - gm

    teleport:
        description: "Teleportiere dich zu einem Spieler."
        usage: "/<command> <spieler,location>"
        aliases:
            - tp

    msg:
        description: "Sende eine private Nachricht."
        usage: "/<command> <spieler> <nachricht>"
        aliases:
            - m
            - tell
            - whisper
            - w

    reply:
        description: "Antworte auf eine private Nachricht."
        usage: "/<command> <nachricht>"
        aliases:
            - r

    tpall:
        description: "Teleportiere alle Online-Spieler zu dir."
        usage: "/tpall"

    tpaall:
        description: "Fordere alle Online-Spieler an, sich zu dir zu teleportieren."
        usage: "/tpaall"

    tpahere:
        description: "Fordere einen Spieler an, sich zu dir zu teleportieren."
        usage: "/tpahere <player>"

    tpacancel:
        description: "Storniere eine Teleportanfrage."
        usage: "/tpacancel [player]"

    tpa:
        description: "Fordere einen Spieler an, sich zu dir zu teleportieren."
        usage: "/tpa <player>"

    tpaccept:
        description: "Akzeptiere eine Teleportanfrage."
        usage: "/tpaccept"

    tpauto:
        description: "Aktiviere das automatische Akzeptieren von Teleportanfragen."
        usage: "/tpauto"

    language:
        description: "Ändere deine Sprache."
        usage: "/language <language>"
        aliases:
            - lang

    day:
        description: "Setze die Zeit auf Tag."
        usage: "/day"

    night:
        description: "Setze die Zeit auf Nacht."
        usage: "/night"

    sunrise:
        description: "Setze die Zeit auf Sonnenaufgang."
        usage: "/sunrise"

    sunset:
        description: "Setze die Zeit auf Sonnenuntergang."
        usage: "/sunset"

    sun:
        description: "Setze das Wetter auf Klar."
        usage: "/sun"

    rain:
        description: "Setze das Wetter auf Regen."
        usage: "/rain"

    thunder:
        description: "Setze das Wetter auf Gewitter."
        usage: "/thunder"

    time:
        description: "Setze die Zeit."
        usage: "/time <zeit> [welt]"

    weather:
        description: "Setze das Wetter."
        usage: "/weather <wetter> [welt | time]"

    heal:
        description: "Heile dich."
        usage: "/heal [spieler]"

    feed:
        description: "Füttere dich."
        usage: "/feed [spieler]"

    fly:
        description: "Gebe dir die Power zum Fliegen oder entneheme sie dir wieder"
        usage: "/fly [player]"

    godmode:
        description: "Sei der unbesigbare auf dem ganzen Server"
        usage: "/godmode [player]"
        aliases:
            - god

    reboot:
        description: "Fahre dein Server Runter"
        usage: "/reboot [time]"
        aliases:
            - restart
            - stop
            - shutdown

    broadcast:
        description: "Sende eine Nachricht an alle Spieler."
        usage: "/broadcast <nachricht> [-l LANG]"
        aliases:
            - alert
            - bc

    invsee:
        description: "Öffne das Inventar eines anderen Spielers."
        usage: "/invsee <Spieler>"

    sitlay:

    sit:

    lay:

    status:

    spawn:

    warp:

    chat:

    chatclear:
        description: "Leert den Chat für alle oder bestimmte Sprachen"
        usage: "/chatclear [-l <sprache>] [-t <sekunden>]"
        aliases: [cc]





permissions:
    aps.admin:
        description: "Permission for all admin commands"
        default: op
    aps.user:
        description: "Permission for all user commands"
        default: true
    aps.command.minecraft:
        description: "Permission for all commands with minecraft: prefix"
        default: false
    aps.command.reply:
        description: "Permission to reply to private messages"
        default: true
    aps.command.msg:
        description: "Permission to send private messages"
        default: true
    aps.command.msg.receive:
        description: "Permission to receive private messages"
        default: true
    aps.command.msg.send:
        description: "Permission to send private messages"
        default: true
    aps.command.teleport:
        description: "Permission to teleport to players"
        default: op
    aps.command.gamemode:
        description: "Permission to change the gamemode"
        default: op
    aps.command.tpall:
        description: "Erlaubt es einem Spieler, den tpall-Befehl zu verwenden."
        default: true
    aps.command.tpaall:
        description: "Erlaubt es einem Spieler, den tpaall-Befehl zu verwenden."
        default: op
    aps.command.tpahere:
        description: "Erlaubt es einem Spieler, den tpahere-Befehl zu verwenden."
        default: true
    aps.command.tpacancel:
        description: "Erlaubt es einem Spieler, den tpacancel-Befehl zu verwenden."
        default: true
    aps.command.tpa:
        description: "Erlaubt es einem Spieler, den tpa-Befehl zu verwenden."
        default: true
    aps.command.tpaccept:
        description: "Erlaubt es einem Spieler, den tpaccept-Befehl zu verwenden."
        default: true
    aps.command.tpauto:
        description: "Erlaubt es einem Spieler, den tpauto-Befehl zu verwenden."
        default: op